[package]
name = "bert-test"
version = "0.1.0"
authors = ["benjamin <benjamin@leveritt.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.14.0"
anyhow = "1.0.40"
